# Change these first
owner: marcelmichau # Your GitHub username
repo: home-page-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: marcelmichau
    url: https://marcelmichau.dev

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /home-page-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status Page for Marcel Michau Home Page"
  introMessage: This is a status page for monitoring the uptime of my personal website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
